const scholarships = [
   {
    "id": 1,
    "title": "University of Arizona Scholarships 2025-2026",
    "amount": "$4,000 - $35,000 per academic year (Global Wildcat Award)",
    "deadline": "Various (See table)",
    "location": "USA 🇺🇸",
    "level": "Bachelor, Graduate",
    "tags": ["Bachelor", "Master", "PhD", "International Students", "US Citizens"],
    "description": "Scholarships for international students and US citizens, offering the Global Wildcat Award ($4,000-$35,000 per year) and covering a wide range of academic fields. The application is entirely online.",
    "link": "Official Website (Details to be confirmed)",
    "views": "12,405",
    "date": "Dec 9, 2025",
    "details": {
        "benefits": [
            "Global Wildcat Award ($4,000-$35,000 per academic year for first-year)",
            "Society of Women Engineers",
            "Scholarship Universe",
            "International Student Loans",
            "Sponsorship"
        ],
        "eligibility_criteria": [
            "International students, as well as US citizens, can apply.",
            "Must have a High School Degree for a Bachelor applying.",
            "Must have a Bachelor’s degree if applying for Graduate."
        ],
        "available_courses": [
            "Computer and information science",
            "Engineering and Technology",
            "Mathematics, statistics, and data science",
            "Education and human development",
            "Culture and language",
            "Communication, Journalism",
            "Health, Nutrition, Fitness",
            "Environment and sustainability",
            "Agriculture Sciences",
            "Animal and Veterinary Sciences",
            "Agriculture Planning and development",
            "Arts and Media",
            "Bio and biomedical science",
            "Business, economics",
            "English Literature",
            "Law, Policy, and Social Justice",
            "Social and Behaviour Science",
            "Physical and space science",
            "Philosophy and religious studies",
            "Psychology"
        ],
        "application_deadlines": [
            {
                "term": "Summer 2024",
                "term_dates": "May 13, 2024–Aug. 6, 2025",
                "deadline_date": "July 29, 2025"
            },
            {
                "term": "2025–26 fall/spring academic year",
                "term_dates": "August 2025–May 2026",
                "deadline_date": "May 1, 2026"
            },
            {
                "term": "Fall 2025 only",
                "term_dates": "August–December 2025",
                "deadline_date": "Dec. 5, 2025"
            },
            {
                "term": "Spring 2026 only",
                "term_dates": "January–May 2026",
                "deadline_date": "May 1, 2026"
            }
        ],
        "how_to_apply": "The application process is completed Online. Fill out the application form along with the required documents. Visit the official website for details."
    }
}
    {
        id: 2,
        title: "Japan Education Pathways Scholarship",
        amount: "Full Tuition + Stipend",
        deadline: "Open",
        location: "Japan 🇯🇵",
        level: "bachelor",
        tags: ["Refugee Students", "Accommodation"],
        description: "Full coverage of tuition, fees, on-campus accommodation, and monthly stipend for refugee students.",
        link: "https://grabscholarships.com/eps-scholarship-for-refugee-students/",
        views: "8,932",
        date: "Nov 19, 2025"
    },
    {
        id: 3,
        title: "Notre Dame University Scholarships",
        amount: "Funded",
        deadline: "Open",
        location: "Australia 🇦🇺",
        level: "bachelor",
        tags: ["Undergraduate", "Master"],
        description: "Scholarships available for Undergraduate and Master’s degrees at Notre Dame University, Australia.",
        link: "https://grabscholarships.com/notre-dame-university-scholarships-in-australia/",
        views: "5,100",
        date: "Nov 18, 2025"
    },
    {
        id: 4,
        title: "University of Oregon ICSP Scholarship",
        amount: "Fully Funded",
        deadline: "Feb 14, 2026",
        location: "USA 🇺🇸",
        level: "bachelor",
        tags: ["Bachelor", "Master", "PhD"],
        description: "Fully funded study in the USA for Bachelor’s, Master’s, and Doctoral degrees.",
        link: "https://grabscholarships.com/university-of-oregon-icsp-scholarship/",
        views: "15,230",
        date: "Nov 17, 2025"
    },
    {
        id: 5,
        title: "Radboud Scholarship Program",
        amount: "Partially Funded",
        deadline: "Jan 31, 2026",
        location: "Netherlands 🇳🇱",
        level: "master",
        tags: ["Master", "Visa Covered"],
        description: "Tuition fee reduced to €2,530. Covers visa costs, residence permit, and insurance.",
        link: "https://grabscholarships.com/radboud-university-scholarship/",
        views: "4,500",
        date: "Nov 16, 2025"
    },
    {
        id: 6,
        title: "Asia Pacific University MEXT Scholarship",
        amount: "Fully Funded",
        deadline: "Nov 12, 2025",
        location: "Japan 🇯🇵",
        level: "bachelor",
        tags: ["Master", "PhD", "MEXT"],
        description: "MEXT Scholarship for Bachelors, Masters, and PhD degrees at APU Japan.",
        link: "https://grabscholarships.com/asia-pacific-university-mext-scholarship/",
        views: "22,100",
        date: "Nov 15, 2025"
    },
    {
        id: 7,
        title: "Portland State University Retention",
        amount: "$1,500/term",
        deadline: "Open",
        location: "USA 🇺🇸",
        level: "bachelor",
        tags: ["Partial", "Renewable"],
        description: "Partial tuition scholarship of $1,500 per term, renewable for up to six terms.",
        link: "https://grabscholarships.com/international-student-retention-scholarship/",
        views: "3,200",
        date: "Nov 14, 2025"
    },
    {
        id: 8,
        title: "Maitri Fellowship Program 2026",
        amount: "Funded",
        deadline: "Jan 14, 2026",
        location: "Australia 🇦🇺",
        level: "master",
        tags: ["India Specific", "Research"],
        description: "Fellowship program by Centre for Australia-India Relations for Indian nationals.",
        link: "https://grabscholarships.com/maitri-fellowship-program/",
        views: "6,700",
        date: "Nov 13, 2025"
    },
    {
        id: 9,
        title: "Wageningen University Africa Scholarship",
        amount: "Fully Funded",
        deadline: "Open",
        location: "Netherlands 🇳🇱",
        level: "master",
        tags: ["Africa Specific", "Travel", "Stipend"],
        description: "Covers travel, living allowance, tuition, visa, and health insurance for 24 months.",
        link: "https://grabscholarships.com/africa-scholarship-programme-at-wageningen-university/",
        views: "18,900",
        date: "Nov 12, 2025"
    },
    {
        id: 10,
        title: "SNU Samsung Scholarship 2026",
        amount: "Funded",
        deadline: "Oct 20, 2025",
        location: "South Korea 🇰🇷",
        level: "master",
        tags: ["Master", "PhD"],
        description: "Funded scholarship for Masters and PhD students at Seoul National University.",
        link: "https://grabscholarships.com/snu-samsung-scholarship/",
        views: "9,450",
        date: "Nov 11, 2025"
    },
    {
        id: 11,
        title: "Oxford Optiver Foundation Scholarship",
        amount: "Funded",
        deadline: "Jan 2026",
        location: "UK 🇬🇧",
        level: "master",
        tags: ["Master", "STEM"],
        description: "Scholarship for Master's degree students at Oxford University.",
        link: "https://grabscholarships.com/oxford-optiver-foundation-scholarship/",
        views: "11,200",
        date: "Nov 10, 2025"
    },
    {
        id: 12,
        title: "University of Michigan Scholarships",
        amount: "Multiple Programs",
        deadline: "Varies",
        location: "USA 🇺🇸",
        level: "bachelor",
        tags: ["No IELTS", "Master", "PhD"],
        description: "Multiple scholarship programs for Undergraduate, Masters and PhD studies.",
        link: "https://grabscholarships.com/university-of-michigan-scholarships/",
        views: "25,600",
        date: "Nov 09, 2025"
    },
    {
        id: 13,
        title: "Chulalongkorn University Scholarships",
        amount: "Fully Funded",
        deadline: "Oct 31, 2025",
        location: "Thailand 🇹🇭",
        level: "master",
        tags: ["Master", "PhD"],
        description: "Fully funded scholarships for international students in Thailand.",
        link: "https://grabscholarships.com/chulalongkorn-university-scholarships/",
        views: "7,800",
        date: "Nov 08, 2025"
    },
    {
        id: 14,
        title: "Deakin University Vice-Chancellor",
        amount: "Fully Funded",
        deadline: "All Year",
        location: "Australia 🇦🇺",
        level: "master",
        tags: ["Master", "PhD"],
        description: "International Vice-Chancellor Scholarship accepted all year round.",
        link: "https://grabscholarships.com/deakin-university-international-vice-chancellor-scholarship/",
        views: "5,900",
        date: "Nov 07, 2025"
    },
    {
        id: 15,
        title: "York University Int. Scholarships",
        amount: "$30k - $45k",
        deadline: "Feb 15, 2026",
        location: "Canada 🇨🇦",
        level: "bachelor",
        tags: ["Undergraduate", "Merit"],
        description: "Provides significant financial support, up to $180,000 over four years for top students.",
        link: "https://grabscholarships.com/york-university-international-student-scholarships/",
        views: "14,300",
        date: "Nov 06, 2025"
    },
    {
        id: 16,
        title: "Nursing Scholarships in Canada",
        amount: "Fully Funded",
        deadline: "Varies",
        location: "Canada 🇨🇦",
        level: "bachelor",
        tags: ["Nursing", "Health"],
        description: "Top fully funded opportunities specifically for nursing students in Canada.",
        link: "https://grabscholarships.com/nursing-scholarships-in-canada/",
        views: "28,100",
        date: "Nov 05, 2025"
    },
    {
        id: 17,
        title: "Ontario Graduate Scholarship 2026",
        amount: "Funded",
        deadline: "Varies",
        location: "Canada 🇨🇦",
        level: "master",
        tags: ["Master", "PhD", "Government"],
        description: "Funded by the Government of Ontario for Master and PhD students.",
        link: "https://grabscholarships.com/ontario-graduate-scholarship/",
        views: "6,200",
        date: "Nov 04, 2025"
    },
    {
        id: 18,
        title: "Erasmus Mundus CYBERMACS",
        amount: "Fully Funded",
        deadline: "Varies",
        location: "Europe 🇪🇺",
        level: "master",
        tags: ["Cybersecurity", "Travel"],
        description: "Covers airfare, accommodation, visa, stipend, and tuition fees. Host countries: Turkey, North Macedonia, Germany.",
        link: "https://grabscholarships.com/erasmus-mundus-cybermax-scholarship/",
        views: "3,400",
        date: "Nov 03, 2025"
    },
    {
        id: 19,
        title: "SI Swedish Institute Scholarships",
        amount: "Fully Funded",
        deadline: "Feb 25, 2026",
        location: "Sweden 🇸🇪",
        level: "master",
        tags: ["Government", "300 Awards"],
        description: "Fully funded master's degree scholarships by the Swedish Government.",
        link: "https://grabscholarships.com/the-swedish-government-scholarship/",
        views: "10,500",
        date: "Nov 02, 2025"
    },
    {
        id: 20,
        title: "University of Saskatchewan 2026",
        amount: "Funded",
        deadline: "Feb 1, 2026",
        location: "Canada 🇨🇦",
        level: "bachelor",
        tags: ["Master", "PhD"],
        description: "Funded scholarships for Bachelors, Masters, and PhD students in Canada.",
        link: "https://grabscholarships.com/university-of-saskatchewan-scholarships/",
        views: "8,100",
        date: "Nov 01, 2025"
    },
    {
        id: 21,
        title: "Erasmus Mundus NOHA 2026",
        amount: "Fully Funded",
        deadline: "Dec 15, 2025",
        location: "Europe 🇪🇺",
        level: "master",
        tags: ["Humanitarian", "Joint Degree"],
        description: "Master’s Degree in International Humanitarian Action. Hosts include France, Netherlands, Germany, etc.",
        link: "https://grabscholarships.com/erasmus-mundus-noha-scholarship/",
        views: "4,800",
        date: "Oct 31, 2025"
    },
    {
        id: 22,
        title: "Taiwan International Graduate",
        amount: "Fully Funded",
        deadline: "Feb 01, 2026",
        location: "Taiwan 🇹🇼",
        level: "master",
        tags: ["PhD", "100 Awards"],
        description: "Fully funded Graduate Scholarship for International Students in Taiwan.",
        link: "https://grabscholarships.com/taiwan-international-graduate-scholarship/",
        views: "3,900",
        date: "Oct 30, 2025"
    },
    {
        id: 23,
        title: "Hamad Bin Khalifa University",
        amount: "Fully Funded",
        deadline: "Feb 1, 2026",
        location: "Qatar 🇶🇦",
        level: "bachelor",
        tags: ["Master", "PhD"],
        description: "Comprehensive scholarship coverage for all degree levels in Qatar.",
        link: "https://grabscholarships.com/hamad-bin-khalifa-university-scholarship/",
        views: "5,600",
        date: "Oct 29, 2025"
    },
    {
        id: 24,
        title: "Full Ride USA Scholarship 2026",
        amount: "Fully Funded",
        deadline: "Varies",
        location: "USA 🇺🇸",
        level: "bachelor",
        tags: ["Master", "PhD", "Full Ride"],
        description: "Various full ride scholarships at American Universities for international students.",
        link: "https://grabscholarships.com/full-ride-usa-scholarship/",
        views: "30,200",
        date: "Oct 28, 2025"
    },
    {
        id: 25,
        title: "AUC Egypt Education Scholarship",
        amount: "Funded",
        deadline: "Nov 15, 2025",
        location: "Egypt 🇪🇬",
        level: "bachelor",
        tags: ["Undergraduate"],
        description: "Donor-funded scholarships for prospective students at The American University in Cairo.",
        link: "https://grabscholarships.com/egypt-education-scholarship/",
        views: "2,300",
        date: "Oct 27, 2025"
    },
    {
        id: 26,
        title: "Harvard PhD & Postdoc",
        amount: "Fully Funded",
        deadline: "Varies",
        location: "USA 🇺🇸",
        level: "phd",
        tags: ["Postdoc", "Stipend"],
        description: "Includes generous annual stipend, research support, and health insurance.",
        link: "https://grabscholarships.com/vard-university-phd-and-postdoctoral-scholarships/",
        views: "45,000",
        date: "Oct 26, 2025"
    },
    {
        id: 27,
        title: "Chongqing University CSC",
        amount: "Fully Funded",
        deadline: "Mar 31, 2026",
        location: "China 🇨🇳",
        level: "master",
        tags: ["CSC", "PhD", "Stipend"],
        description: "Chinese Government Scholarship covering tuition, accommodation, and stipend.",
        link: "https://grabscholarships.com/chongqing-university-csc-scholarship/",
        views: "6,100",
        date: "Oct 25, 2025"
    },
    {
        id: 28,
        title: "NPU International Scholarships",
        amount: "Fully Funded",
        deadline: "Feb/Mar 2026",
        location: "China 🇨🇳",
        level: "bachelor",
        tags: ["Master", "PhD"],
        description: "Fully funded scholarships at Northwestern Polytechnical University.",
        link: "https://grabscholarships.com/northwestern-polytechnical-university-scholarships/",
        views: "4,400",
        date: "Oct 24, 2025"
    },
    {
        id: 29,
        title: "Ghent University PhD",
        amount: "Funded",
        deadline: "Feb 17, 2026",
        location: "Belgium 🇧🇪",
        level: "phd",
        tags: ["Research"],
        description: "PhD scholarship opportunities at Ghent University for international candidates.",
        link: "https://grabscholarships.com/ghent-university-phd-scholarships/",
        views: "2,900",
        date: "Oct 23, 2025"
    },
    {
        id: 30,
        title: "Chalmers IPOET Scholarships",
        amount: "75% Tuition Waiver",
        deadline: "Jan 17, 2026",
        location: "Sweden 🇸🇪",
        level: "master",
        tags: ["Tuition Waiver"],
        description: "Significant tuition reduction for non-EU/EEA Master's students.",
        link: "https://grabscholarships.com/chalmers-ipoet-scholarships/",
        views: "7,100",
        date: "Oct 22, 2025"
    },
    {
        id: 31,
        title: "University of Cambridge Mastercard",
        amount: "Fully Funded",
        deadline: "Dec/Jan 2026",
        location: "UK 🇬🇧",
        level: "master",
        tags: ["Africa Specific", "Travel"],
        description: "Fully funded program for African students covering tuition, travel, and living costs.",
        link: "https://grabscholarships.com/university-of-cambridge-mastercard-foundation-scholars-program/",
        views: "35,400",
        date: "Oct 21, 2025"
    },
    {
        id: 32,
        title: "University of Sheffield GEMS",
        amount: "Funded",
        deadline: "Feb 16, 2026",
        location: "UK 🇬🇧",
        level: "bachelor",
        tags: ["Undergraduate"],
        description: "GEMS Scholarship for international undergraduate students at Sheffield.",
        link: "https://grabscholarships.com/university-of-sheffield-gems-scholarship/",
        views: "5,300",
        date: "Oct 20, 2025"
    },
    {
        id: 33,
        title: "Amazon Future Engineer",
        amount: "$40,000",
        deadline: "Jan 15, 2026",
        location: "USA 🇺🇸",
        level: "bachelor",
        tags: ["STEM", "Computer Science"],
        description: "Award of $40,000 for students pursuing computer science degrees.",
        link: "https://grabscholarships.com/amazon-future-engineer-scholarship/",
        views: "50,200",
        date: "Oct 19, 2025"
    },
    {
        id: 34,
        title: "Chevening Scholarships 2026",
        amount: "Fully Funded",
        deadline: "Nov 5, 2026",
        location: "UK 🇬🇧",
        level: "master",
        tags: ["UK Government", "Leaders"],
        description: "Fully funded scholarships to undertake any master's course at any UK university.",
        link: "https://www.chevening.org/scholarship/",
        views: "95,400",
        date: "Oct 18, 2025"
    }

];
